In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.set_random_seed(777)

In [3]:
#Nomalization function
def MinMaxScaler(data):
    numerator = data - np.min(data,0)
    denominator = np.max(data,0) -np.min(data,0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7) 

In [4]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [5]:
xy = MinMaxScaler(xy)
print(xy)

[[ 0.99999999  0.99999999  0.          1.          1.        ]
 [ 0.70548491  0.70439552  1.          0.71881782  0.83755791]
 [ 0.54412549  0.50274824  0.57608696  0.606468    0.6606331 ]
 [ 0.33890353  0.31368023  0.10869565  0.45989134  0.43800918]
 [ 0.51436     0.42582389  0.30434783  0.58504805  0.42624401]
 [ 0.49556179  0.42582389  0.31521739  0.48131134  0.49276137]
 [ 0.11436064  0.          0.20652174  0.22007776  0.18597238]
 [ 0.          0.07747099  0.5326087   0.          0.        ]]


In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [7]:
X = tf.placeholder(tf.float32, shape = [None,4])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([4,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name= 'bias')

In [8]:
#hypothesis
hypothesis = tf.matmul(X,W)

In [9]:
#cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(201):
    cost_val, hy_val, _ = sess.run([cost, hypothesis,train], feed_dict={X:x_data, Y: y_data})
    print(step, " Cost: ", cost_val, "\n Prediction: \n", hy_val)

0  Cost:  0.362424 
 Prediction: 
 [[ 1.17613995]
 [-0.39234215]
 [-0.10839732]
 [ 0.21224611]
 [ 0.15282832]
 [ 0.15616494]
 [-0.22675946]
 [-0.59576273]]
1  Cost:  0.362416 
 Prediction: 
 [[ 1.17615175]
 [-0.39232814]
 [-0.10838749]
 [ 0.21225108]
 [ 0.15283613]
 [ 0.15617225]
 [-0.2267569 ]
 [-0.59575945]]
2  Cost:  0.362408 
 Prediction: 
 [[ 1.17616343]
 [-0.39231399]
 [-0.10837764]
 [ 0.21225613]
 [ 0.15284392]
 [ 0.15617959]
 [-0.22675434]
 [-0.59575611]]
3  Cost:  0.3624 
 Prediction: 
 [[ 1.17617524]
 [-0.39229998]
 [-0.10836792]
 [ 0.21226113]
 [ 0.15285167]
 [ 0.15618691]
 [-0.22675179]
 [-0.59575278]]
4  Cost:  0.362392 
 Prediction: 
 [[ 1.17618692]
 [-0.39228597]
 [-0.10835814]
 [ 0.21226613]
 [ 0.15285939]
 [ 0.15619418]
 [-0.22674921]
 [-0.59574944]]
5  Cost:  0.362384 
 Prediction: 
 [[ 1.17619872]
 [-0.39227185]
 [-0.10834825]
 [ 0.21227115]
 [ 0.15286717]
 [ 0.1562015 ]
 [-0.22674666]
 [-0.5957461 ]]
6  Cost:  0.362377 
 Prediction: 
 [[ 1.1762104 ]
 [-0.39225784]
 