In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [4]:
hypothesis = tf.matmul(X, W) + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()

In [8]:
sess.run(tf.global_variables_initializer())

In [11]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis, train], feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  24556.2 
Prediction:
 [[ 18.96166039]
 [ 13.79047298]
 [ 18.74181175]
 [ 12.58879757]
 [ 15.01425838]]
10 Cost:  16.464 
Prediction:
 [[ 157.52870178]
 [ 180.35679626]
 [ 182.85240173]
 [ 191.30387878]
 [ 142.06488037]]
20 Cost:  16.2023 
Prediction:
 [[ 157.93780518]
 [ 180.86758423]
 [ 183.34565735]
 [ 191.84371948]
 [ 142.45698547]]
30 Cost:  16.1654 
Prediction:
 [[ 157.92893982]
 [ 180.87590027]
 [ 183.34385681]
 [ 191.84449768]
 [ 142.46578979]]
40 Cost:  16.1287 
Prediction:
 [[ 157.9188385 ]
 [ 180.88273621]
 [ 183.34059143]
 [ 191.84365845]
 [ 142.47341919]]
50 Cost:  16.0922 
Prediction:
 [[ 157.90870667]
 [ 180.88945007]
 [ 183.33728027]
 [ 191.84272766]
 [ 142.48098755]]
60 Cost:  16.0558 
Prediction:
 [[ 157.89860535]
 [ 180.89619446]
 [ 183.33396912]
 [ 191.84185791]
 [ 142.48857117]]
70 Cost:  16.0198 
Prediction:
 [[ 157.88864136]
 [ 180.90296936]
 [ 183.33073425]
 [ 191.84101868]
 [ 142.49613953]]
80 Cost:  15.9837 
Prediction:
 [[ 157.87860107]
 [ 180.9096832

980 Cost:  13.3422 
Prediction:
 [[ 157.07298279]
 [ 181.44827271]
 [ 183.06315613]
 [ 191.78393555]
 [ 143.09672546]]
990 Cost:  13.3184 
Prediction:
 [[ 157.06498718]
 [ 181.45359802]
 [ 183.06053162]
 [ 191.78352356]
 [ 143.10243225]]
1000 Cost:  13.2948 
Prediction:
 [[ 157.05705261]
 [ 181.45890808]
 [ 183.0579071 ]
 [ 191.78309631]
 [ 143.10813904]]
1010 Cost:  13.2714 
Prediction:
 [[ 157.04914856]
 [ 181.46417236]
 [ 183.05529785]
 [ 191.78268433]
 [ 143.11383057]]
1020 Cost:  13.248 
Prediction:
 [[ 157.04124451]
 [ 181.46943665]
 [ 183.05267334]
 [ 191.7822876 ]
 [ 143.11950684]]
1030 Cost:  13.2248 
Prediction:
 [[ 157.03335571]
 [ 181.47471619]
 [ 183.05007935]
 [ 191.78187561]
 [ 143.12513733]]
1040 Cost:  13.2015 
Prediction:
 [[ 157.02548218]
 [ 181.47996521]
 [ 183.04747009]
 [ 191.78147888]
 [ 143.13076782]]
1050 Cost:  13.1786 
Prediction:
 [[ 157.01766968]
 [ 181.48521423]
 [ 183.04489136]
 [ 191.78108215]
 [ 143.13641357]]
1060 Cost:  13.1556 
Prediction:
 [[ 157.00

1780 Cost:  11.7372 
Prediction:
 [[ 156.49433899]
 [ 181.83314514]
 [ 182.87069702]
 [ 191.76220703]
 [ 143.50263977]]
1790 Cost:  11.7203 
Prediction:
 [[ 156.48777771]
 [ 181.83744812]
 [ 182.86853027]
 [ 191.76210022]
 [ 143.50712585]]
1800 Cost:  11.7035 
Prediction:
 [[ 156.48124695]
 [ 181.84176636]
 [ 182.86633301]
 [ 191.76196289]
 [ 143.5115509 ]]
1810 Cost:  11.6869 
Prediction:
 [[ 156.47477722]
 [ 181.84606934]
 [ 182.86412048]
 [ 191.76184082]
 [ 143.51599121]]
1820 Cost:  11.6702 
Prediction:
 [[ 156.46829224]
 [ 181.85038757]
 [ 182.86195374]
 [ 191.76171875]
 [ 143.52041626]]
1830 Cost:  11.6537 
Prediction:
 [[ 156.46180725]
 [ 181.85466003]
 [ 182.8598175 ]
 [ 191.76158142]
 [ 143.52481079]]
1840 Cost:  11.6371 
Prediction:
 [[ 156.45532227]
 [ 181.85896301]
 [ 182.85760498]
 [ 191.76147461]
 [ 143.5291748 ]]
1850 Cost:  11.6208 
Prediction:
 [[ 156.44892883]
 [ 181.86320496]
 [ 182.85546875]
 [ 191.76135254]
 [ 143.53353882]]
1860 Cost:  11.6044 
Prediction:
 [[ 156