In [1]:
import tensorflow as tf

In [3]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.x1 = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [4]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#reduce mean =평균

In [6]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()

In [8]:
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],\
                                  feed_dict ={x1:x1_data,x2:x2_data,x3:x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n",hy_val)

0 Cost:  59965.2 
Prediction:
 [-61.74960327 -79.37811279 -75.49416351 -81.95510101 -62.21759415]
10 Cost:  11.7954 
Prediction:
 [ 154.84048462  180.97061157  181.0196228   197.38302612  136.36793518]
20 Cost:  11.1894 
Prediction:
 [ 155.48339844  181.76687622  181.79199219  198.22512817  136.9803009 ]
30 Cost:  11.1326 
Prediction:
 [ 155.47296143  181.77780151  181.79057312  198.22460938  136.99362183]
40 Cost:  11.076 
Prediction:
 [ 155.46058655  181.78634644  181.78683472  198.22155762  137.00511169]
50 Cost:  11.0198 
Prediction:
 [ 155.44822693  181.79484558  181.78311157  198.21850586  137.01657104]
60 Cost:  10.9639 
Prediction:
 [ 155.43591309  181.80331421  181.77935791  198.2154541   137.02798462]
70 Cost:  10.9083 
Prediction:
 [ 155.42364502  181.81176758  181.77563477  198.21240234  137.03936768]
80 Cost:  10.853 
Prediction:
 [ 155.41139221  181.82022095  181.77194214  198.2093811   137.05073547]
90 Cost:  10.798 
Prediction:
 [ 155.39916992  181.82862854  181.7682495

1000 Cost:  6.8522 
Prediction:
 [ 154.41693115  182.50517273  181.47131348  197.96009827  137.97650146]
1010 Cost:  6.81871 
Prediction:
 [ 154.40745544  182.51170349  181.46846008  197.95768738  137.98538208]
1020 Cost:  6.7854 
Prediction:
 [ 154.39797974  182.51821899  181.46557617  197.95527649  137.99420166]
1030 Cost:  6.75225 
Prediction:
 [ 154.3885498   182.52471924  181.46273804  197.95288086  138.0030365 ]
1040 Cost:  6.71924 
Prediction:
 [ 154.37913513  182.53121948  181.4598999   197.95046997  138.01184082]
1050 Cost:  6.68647 
Prediction:
 [ 154.36975098  182.53768921  181.45707703  197.9480896   138.02061462]
1060 Cost:  6.6539 
Prediction:
 [ 154.3604126   182.54412842  181.45425415  197.94570923  138.02935791]
1070 Cost:  6.62143 
Prediction:
 [ 154.35105896  182.55056763  181.45143127  197.94332886  138.03808594]
1080 Cost:  6.58917 
Prediction:
 [ 154.3417511   182.55696106  181.44862366  197.94094849  138.04679871]
1090 Cost:  6.55707 
Prediction:
 [ 154.33247375 