In [1]:
import tensorflow as tf

In [2]:
tf.set_random_seed(7778)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
nb_classes = 3

In [8]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes], name = 'bias'))

In [9]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [12]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [14]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [16]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict = {X: x_data, Y: y_data})
        if step %200 == 0:
            print(step, sess.run(cost, feed_dict= {X: x_data, Y: y_data}))
      
    print("~~~~~~~~~")
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict = {X:[[1,10,7,9]]})
    print(a, sess.run(tf.arg_max(a,1)))
    
    print("~~~~~~~~")
    
    b = sess.run(hypothesis, feed_dict = {X:[[1,0,2,7]]})
    print(b, sess.run(tf.arg_max(b,1)))
    
    print("~~~~~~~~")
    
    c = sess.run(hypothesis, feed_dict = {X:[[3,2,0,1]]})
    print(c, sess.run(tf.arg_max(c,1)))
    
    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1,10,7,9], [1,0,2,7], [3,2,0,1]]})
    print(all, sess.run(tf.arg_max(all, 1)))

0 8.49943
200 0.650108
400 0.539096
600 0.444866
800 0.353735
1000 0.26595
1200 0.227614
1400 0.207002
1600 0.189683
1800 0.174935
2000 0.162234
~~~~~~~~~
[[  1.34960944e-02   9.86500323e-01   3.49271681e-06]] [1]
~~~~~~~~
[[  3.54673446e-08   9.99765575e-01   2.34450577e-04]] [1]
~~~~~~~~
[[  7.55902472e-16   4.85275052e-07   9.99999523e-01]] [2]
--------------
[[  1.34961195e-02   9.86500323e-01   3.49271681e-06]
 [  3.54672096e-08   9.99765575e-01   2.34450126e-04]
 [  7.55902472e-16   4.85275052e-07   9.99999523e-01]] [1 1 2]
